In [192]:
import pandas as pd

In [193]:
df = pd.read_csv("../data/global_air_quality_2014_2025.csv")
df = df.sort_values(["Country", "City", "Date"])
df.head()

,Country,State,City,Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),...,Toluene (ug/m3),Xylene (ug/m3),AQI,AQI_Bucket,Wind_Speed (km/h),Humidity (%),Deforestation_Rate_%,Industry_Growth_%,CO2_Emission_MT,Population_Density_per_SqKm
34,Australia,South Australia,Adelaide,2014-01-01,17.01,16.64,2.88,5.92,8.79,1.81,...,1.17,1.23,72.0,Satisfactory,20.43,61.30,0.0062,1.52,6.99,171.90
2339,Australia,South Australia,Adelaide,2014-02-01,7.16,9.71,4.78,10.70,15.47,6.81,...,4.16,1.74,17.0,Good,24.55,59.54,0.0043,0.14,5.72,102.32
4644,Australia,South Australia,Adelaide,2014-03-01,6.04,6.66,4.11,8.32,12.43,4.08,...,1.89,1.17,25.0,Good,11.17,50.17,0.0084,1.29,5.39,182.75
6949,Australia,South Australia,Adelaide,2014-04-01,6.48,15.72,3.88,8.81,12.69,2.68,...,3.63,1.14,19.0,Good,21.24,49.47,0.0110,1.42,4.97,35.13
9254,Australia,South Australia,Adelaide,2014-05-01,6.94,10.00,4.34,10.70,15.05,4.55,...,2.80,2.64,15.0,Good,32.69,62.88,0.0042,1.37,6.12,176.44

In [194]:
df.shape

(331920, 24)

In [195]:
len(df["City"].unique())

2270

In [196]:
df[["City"]].groupby("City").value_counts()

City
10th of Ramadan    144
6th of October     144
Aba                144
Abakaliki          144
Abakan             144
                  ...
Zulfi              144
Zunyi              144
Zwickau            144
eMalahleni         144
Évreux             144
Name: count, Length: 2270, dtype: int64

In [197]:
df[["City"]].groupby("City").value_counts().to_frame().groupby("count").value_counts()

count
144    2236
288      33
432       1
Name: count, dtype: int64

In [198]:
df.columns

Index(['Country', 'State', 'City', 'Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)',
       'NO (ug/m3)', 'NO2 (ug/m3)', 'NOx (ppb)', 'NH3 (ug/m3)', 'CO (mg/m3)',
       'SO2 (ug/m3)', 'O3 (ug/m3)', 'Benzene (ug/m3)', 'Toluene (ug/m3)',
       'Xylene (ug/m3)', 'AQI', 'AQI_Bucket', 'Wind_Speed (km/h)',
       'Humidity (%)', 'Deforestation_Rate_%', 'Industry_Growth_%',
       'CO2_Emission_MT', 'Population_Density_per_SqKm'],
      dtype='object')

## Colums by Category
Index: 
- Country
- State
- City
- Date

Data: 
- PM2.5 (ug/m3)
- PM10 (ug/m3)
- NO (ug/m3)
- NO2 (ug/m3)
- NOx (ppb)
- NH3 (ug/m3)
- CO (mg/m3)
- SO2 (ug/m3)
- O3 (ug/m3)
- Benzene (ug/m3)
- Toluene (ug/m3)
- Xylene (ug/m3)
- AQI
- Wind_Speed (km/h)
- Humidity (%)
- Deforestation_Rate_%
- Industry_Growth_%
- CO2_Emission_MT

Context:
- Population_Density_per_SqKm

Supplement:
- AQI_Bucket -> AQI categorized

In [199]:
df.dtypes

Country                         object
State                           object
City                            object
Date                            object
PM2.5 (ug/m3)                  float64
PM10 (ug/m3)                   float64
NO (ug/m3)                     float64
NO2 (ug/m3)                    float64
NOx (ppb)                      float64
NH3 (ug/m3)                    float64
CO (mg/m3)                     float64
SO2 (ug/m3)                    float64
O3 (ug/m3)                     float64
Benzene (ug/m3)                float64
Toluene (ug/m3)                float64
Xylene (ug/m3)                 float64
AQI                            float64
AQI_Bucket                      object
Wind_Speed (km/h)              float64
Humidity (%)                   float64
Deforestation_Rate_%           float64
Industry_Growth_%              float64
CO2_Emission_MT                float64
Population_Density_per_SqKm    float64
dtype: object

In [200]:
df.isna().sum()

Country                        0
State                          0
City                           0
Date                           0
PM2.5 (ug/m3)                  0
PM10 (ug/m3)                   0
NO (ug/m3)                     0
NO2 (ug/m3)                    0
NOx (ppb)                      0
NH3 (ug/m3)                    0
CO (mg/m3)                     0
SO2 (ug/m3)                    0
O3 (ug/m3)                     0
Benzene (ug/m3)                0
Toluene (ug/m3)                0
Xylene (ug/m3)                 0
AQI                            0
AQI_Bucket                     0
Wind_Speed (km/h)              0
Humidity (%)                   0
Deforestation_Rate_%           0
Industry_Growth_%              0
CO2_Emission_MT                0
Population_Density_per_SqKm    0
dtype: int64

In [201]:
city = pd.read_csv("../data/worldcities.csv")
city.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.1753,106.8269,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6600,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Chongqing,Chongqing,29.5500,106.5069,China,CN,CHN,Chongqing,admin,32054159.0,1156936556
4,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133

In [202]:
supplement = pd.read_csv("../data/worldcities_supplement.csv")
supplement.head()

                city         city_ascii        country        lat         lon
0      Jakarta Pusat      Jakarta Pusat      Indonesia  -6.177700  106.840300
1  Chongqing-Yuzhong  Chongqing-Yuzhong          China  29.560454  106.573400
2   Beijing-Chaoyang   Beijing-Chaoyang          China  39.925494  116.441630
3    Shanghai-Pudong    Shanghai-Pudong          China  31.234722  121.506389
4      New York City      New York City  United States  40.694300  -73.924900

In [203]:
city.isnull().sum()

city              0
city_ascii        2
lat               0
lng               0
country           0
iso2             36
iso3              0
admin_name      178
capital       33906
population     1214
id                0
dtype: int64

In [204]:
city = city.rename(columns={"lng": "lon"})
city = city[["city", "city_ascii", "country", "lat", "lon"]]
city = pd.concat([city, supplement], ignore_index=True)
city.head()

        city city_ascii    country      lat       lon
0      Tokyo      Tokyo      Japan  35.6850  139.7514
1    Jakarta    Jakarta  Indonesia  -6.1753  106.8269
2      Delhi      Delhi      India  28.6600   77.2300
3  Chongqing  Chongqing      China  29.5500  106.5069
4  Guangzhou  Guangzhou      China  23.1300  113.2600

In [205]:
city.dtypes

city           object
city_ascii     object
country        object
lat           float64
lon           float64
dtype: object

In [206]:
city["country"] = city["country"].replace("Korea, North", "North Korea")
city["country"] = city["country"].replace("Korea, South", "South Korea")

In [207]:
import unicodedata
import re

In [208]:
def normalize_name(text):
    if not isinstance(text, str):
        return text

    # Remove accents
    text = ''.join(
        c for c in unicodedata.normalize('NFKD', text)
        if not unicodedata.combining(c)
    )

    # Remove anything inside parentheses (including the parentheses)
    text = re.sub(r'\s*\([^)]*\)', '', text)

    # Collapse extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [209]:
df["City"] = df["City"].apply(normalize_name)

In [210]:
city["id"] = city["city_ascii"] + " | " + city["country"]
city.head()

        city city_ascii    country      lat       lon                   id
0      Tokyo      Tokyo      Japan  35.6850  139.7514        Tokyo | Japan
1    Jakarta    Jakarta  Indonesia  -6.1753  106.8269  Jakarta | Indonesia
2      Delhi      Delhi      India  28.6600   77.2300        Delhi | India
3  Chongqing  Chongqing      China  29.5500  106.5069    Chongqing | China
4  Guangzhou  Guangzhou      China  23.1300  113.2600    Guangzhou | China

In [211]:
df["City_id"] = df["City"] + " | " + df["Country"]
df.head()

,Country,State,City,Date,PM2.5 (ug/m3),PM10 (ug/m3),NO (ug/m3),NO2 (ug/m3),NOx (ppb),NH3 (ug/m3),...,Xylene (ug/m3),AQI,AQI_Bucket,Wind_Speed (km/h),Humidity (%),Deforestation_Rate_%,Industry_Growth_%,CO2_Emission_MT,Population_Density_per_SqKm,City_id
34,Australia,South Australia,Adelaide,2014-01-01,17.01,16.64,2.88,5.92,8.79,1.81,...,1.23,72.0,Satisfactory,20.43,61.30,0.0062,1.52,6.99,171.90,Adelaide | Australia
2339,Australia,South Australia,Adelaide,2014-02-01,7.16,9.71,4.78,10.70,15.47,6.81,...,1.74,17.0,Good,24.55,59.54,0.0043,0.14,5.72,102.32,Adelaide | Australia
4644,Australia,South Australia,Adelaide,2014-03-01,6.04,6.66,4.11,8.32,12.43,4.08,...,1.17,25.0,Good,11.17,50.17,0.0084,1.29,5.39,182.75,Adelaide | Australia
6949,Australia,South Australia,Adelaide,2014-04-01,6.48,15.72,3.88,8.81,12.69,2.68,...,1.14,19.0,Good,21.24,49.47,0.0110,1.42,4.97,35.13,Adelaide | Australia
9254,Australia,South Australia,Adelaide,2014-05-01,6.94,10.00,4.34,10.70,15.05,4.55,...,2.64,15.0,Good,32.69,62.88,0.0042,1.37,6.12,176.44,Adelaide | Australia

In [212]:
required_cities = set(df["City_id"].to_list())
available_cities = set(city["id"].to_list())

In [213]:
print("City")
print(f"Available: {len(required_cities.intersection(available_cities))}")
print(f"Unavailable: {len(required_cities - available_cities)}")

City
Available: 1805
Unavailable: 481

In [214]:
required_countries = set(df["Country"].to_list())
available_countries = set(city["country"].to_list())

In [215]:
print("Country")
print(f"Available: {len(required_countries.intersection(available_countries))}")
print(f"Unavailable: {len(required_countries - available_countries)}")

Country
Available: 24
Unavailable: 0

In [216]:
x = city[["country"]].groupby("country").value_counts()

In [217]:
x.to_frame().to_csv("x.csv")

In [218]:
missing_cities = required_cities - available_cities
u_city = df[["Country", "City_id"]].drop_duplicates(subset="City_id")
missing = u_city[u_city["City_id"].isin(missing_cities)][["Country"]].groupby("Country").value_counts()
missing

Country
Australia          1
Bangladesh        30
Brazil             5
China             36
Egypt             78
Ethiopia          42
France             3
Germany            7
India             35
Indonesia         16
Japan             17
Mexico            11
Nigeria           16
Pakistan          15
Philippines       37
Russia            11
Saudi Arabia      48
South Africa      11
South Korea       41
Thailand           6
United Kingdom     9
Vietnam            6
Name: count, dtype: int64

In [219]:
missing_cities

{'10th of Ramadan | Egypt',
 '6th of October | Egypt',
 'Abobo | Ethiopia',
 'Abu Arish | Saudi Arabia',
 'Abu Simbel | Egypt',
 'Abutig | Egypt',
 'Acapulco | Mexico',
 'Ad Dawadimi | Saudi Arabia',
 'Adama | Ethiopia',
 'Ado Ekiti | Nigeria',
 'Afif | Saudi Arabia',
 'Aga | Egypt',
 'Agami | Egypt',
 'Al Ahsa | Saudi Arabia',
 'Al Badai | Saudi Arabia',
 'Al Bukayriyah | Saudi Arabia',
 'Al Ghazalah | Saudi Arabia',
 'Al Quwayiyah | Saudi Arabia',
 'Al Ula | Saudi Arabia',
 'Al Wasta | Egypt',
 'Alamata | Ethiopia',
 'Aleta Wendo | Ethiopia',
 'Allahabad | India',
 'Amanzimtoti | South Africa',
 'Ambo | Ethiopia',
 'Anand Vihar | India',
 'Anantnag | India',
 'Angeles | Philippines',
 'Anyang | China',
 'Aparecida de Goiania | Brazil',
 'Apodaca | Mexico',
 'Arba Minch | Ethiopia',
 'Arish | Egypt',
 'Asayita | Ethiopia',
 'Asella | Ethiopia',
 'Ashmoun | Egypt',
 'Ashulia | Bangladesh',
 'Asnieres-sur-Seine | France',
 'Attock | Pakistan',
 'Axum | Ethiopia',
 'Ayutthaya | Thailand',
 'Badagry | Nigeria',
 'Bader | Saudi Arabia',
 'Bagerhat | Bangladesh',
 'Baguio | Philippines',
 'Bale Robe | Ethiopia',
 'Baltim | Egypt',
 'Bambasi | Ethiopia',
 'Banyumas | Indonesia',
 'Baoji | China',
 'Baqaa | Saudi Arabia',
 'Baramulla | India',
 'Baris | Egypt',
 'Barry | United Kingdom',
 'Batangas City | Philippines',
 'Bathinda | India',
 'Beanibazar | Bangladesh',
 'Beijing-Dongcheng | China',
 'Beijing-Haidian | China',
 'Beijing-Tongzhou | China',
 'Bela-Bela | South Africa',
 'Bengaluru | India',
 'Beni Suef | Egypt',
 'Bensa | Ethiopia',
 'Bhaluka | Bangladesh',
 'Bhubaneswar | India',
 'Bilbeis | Egypt',
 'Bisha | Saudi Arabia',
 'Bishoftu | Ethiopia',
 'Bogura | Bangladesh',
 'Bojonegoro | Indonesia',
 'Borg El Arab | Egypt',
 'Botshabelo | South Africa',
 'Brandenburg an der Havel | Germany',
 'Brunswick | Germany',
 'Bulaq El Dakrour | Egypt',
 'Buqayq | Saudi Arabia',
 'Buraidah | Saudi Arabia',
 'Burayu | Ethiopia',
 'Bwari | Nigeria',
 'Cabanatuan | Philippines',
 'Calbayog | Philippines',
 'Caloocan | Philippines',
 'Cardiff | United Kingdom',
 'Cauayan | Philippines',
 'Central | China',
 'Chamdo | China',
 'Champhai | India',
 'Chapainawabganj | Bangladesh',
 'Cheonan | South Korea',
 'Cherbourg-en-Cotentin | France',
 'Chilgok | South Korea',
 'Cholula | Mexico',
 'Chonburi | Thailand',
 'Chongqing-Jiangbei | China',
 'Chongqing-Shapingba | China',
 'Chongqing-Wanzhou | China',
 'City of London | United Kingdom',
 'Ciudad Juarez | Mexico',
 'Cotabato City | Philippines',
 'Cumilla | Bangladesh',
 'Dagupan | Philippines',
 'Dahab | Egypt',
 'Dairut | Egypt',
 'Dakhla | Egypt',
 'Dammam | Saudi Arabia',
 'Dangjin | South Korea',
 'Danzhou | China',
 'Datong | China',
 'Davao City | Philippines',
 'Debre Markos | Ethiopia',
 'Degehabur | Ethiopia',
 'Dehradun | India',
 'Dekernes | Egypt',
 'Desouk | Egypt',
 'Dessau | Germany',
 'Dessie | Ethiopia',
 'Dharamshala | India',
 'Dharmanagar | India',
 'Dir | Pakistan',
 'Diriyah | Saudi Arabia',
 'Donghae | South Korea',
 'Dumaguete | Philippines',
 'Dumat Al Jandal | Saudi Arabia',
 'Duque de Caxias | Brazil',
 'Durg | India',
 'Edfu | Egypt',
 'Edku | Egypt',
 'Eket | Nigeria',
 'El Alamein | Egypt',
 'El Dabaa | Egypt',
 'El Mahalla El Kubra | Egypt',
 'El Qoseir | Egypt',
 'El Tor | Egypt',
 'Eleme | Nigeria',
 'Esna | Egypt',
 'Faiyum | Egypt',
 'Faqous | Egypt',
 'Farafra | Egypt',
 'Faraskour | Egypt',
 'Fayed | Egypt',
 'Freiburg | Germany',
 'Funabashi | Japan',
 'Gandhinagar | India',
 'Gaya | Nigeria',
 'Gazipur | Bangladesh',
 'Gboko | Nigeria',
 'Geoje | South Korea',
 'Gimcheon | South Korea',
 'Gimhae | South Korea',
 'Gimje | South Korea',
 'Girga | Egypt',
 'Gondar | Ethiopia',
 'Gongju | South Korea',
 'Goseong | South Korea',
 'Gournadi | Bangladesh',
 'Gresik | Indonesia',
 'Grozny | Russia',
 'Guba | Ethiopia',
 'Gumi | South Korea',
 'Gunpo | South Korea',
 'Gunsan | South Korea',
 'Gurugram | India',
 'Gwangmyeong | South Korea',
 'Gyalshing | India',
 'Gyeongju | South Korea',
 'Ha Nam | Vietnam',
 'Haenam | South Korea',
 'Hafar Al Batin | Saudi Arabia',
 'Hai Phong | Vietnam',
 'Haidong | China',
 'Hail | Saudi Arabia',
 'Hakusan | Japan',
 'Halaba Kulito | Ethiopia',
 'Haman | South Korea',
 'Hanakiyah | Saudi Arabia',
 'Hanover | Germany',
 'Hawassa | Ethiopia',
 'Helwan | Egypt',
 'Higashihiroshima | Japan',
 'Higashiosaka | Japan',
 'Hongcheon | South Korea',
 'Hosaena | Ethiopia',
 'Howrah | India',
 'Hub | Pakistan',
 'Hubli-Dharwad | India',
 'Hubuna | Saudi Arabia',
 'Hull | United Kingdom',
 'Hulunbuir | China',
 'Hunza | Pakistan',
 'Hurghada | Egypt',
 'Hwaseong | South Korea',
 'Hwasun | South Korea',
 'Hyderabad | Pakistan',
 'Icheon | South Korea',
 'Ijebu Ode | Nigeria',
 'Iloilo City | Philippines',
 'Imbaba | Egypt',
 'Imizu | Japan',
 'Iriga | Philippines',
 'Isabela City | Philippines',
 'Ishinomaki | Japan',
 'Island Garden City of Samal | Philippines',
 'Itang | Ethiopia',
 'Izhvesk | Russia',
 'Jakarta Barat | Indonesia',
 'Jakarta Selatan | Indonesia',
 'Jakarta Timur | Indonesia',
 'Jakarta Utara | Indonesia',
 'Jashore | Bangladesh',
 'Jecheon | South Korea',
 'Jeju City | South Korea',
 'Jeongeup | South Korea',
 'Jhalokati | Bangladesh',
 'Jhang | Pakistan',
 'Jhenaidah | Bangladesh',
 'Jikawo | Ethiopia',
 'Jilin City | China',
 'Jimma | Ethiopia',
 'Jincheon | South Korea',
 'Jinju | South Korea',
 'Jiuquan | China',
 'Joinville | Brazil',
 'Jowai | India',
 'Jubail | Saudi Arabia',
 'Juchitan | Mexico',
 'Kafr El Dawwar | Egypt',
 'Kafr El Sheikh | Egypt',
 'Kafr El Zayat | Egypt',
 'Kaifeng | China',
 'Kamashi | Ethiopia',
 'Karaikal | India',
 'Karat Konso | Ethiopia',
 'Kariega | South Africa',
 'Kashihara | Japan',
 'Kebri Dahar | Ethiopia',
 'Kendal | Indonesia',
 'Kepulauan Seribu | Indonesia',
 'Khafji | Saudi Arabia',
 'Khairpur | Pakistan',
 'Khamis Mushait | Saudi Arabia',
 'Khanka | Egypt',
 'Kharga | Egypt',
 'Khobar | Saudi Arabia',
 'Khulais | Saudi Arabia',
 "King William's Town | South Africa",
 'Kishoreganj | Bangladesh',
 'Kollam | India',
 'Kom Ombo | Egypt',
 'Komsomolsk-on-Amur | Russia',
 'Kowloon | China',
 'Kozhikode | India',
 'Kudus | Indonesia',
 'Lalmonirhat | Bangladesh',
 'Lapu-Lapu | Philippines',
 'Las Pinas | Philippines',
 'Legazpi | Philippines',
 'Leku | Ethiopia',
 'Leon | Mexico',
 'Lephalale | South Africa',
 'Lijiang | China',
 'Lipa | Philippines',
 'Liupanshui | China',
 'Logia | Ethiopia',
 'Lopburi | Thailand',
 'Maadi | Egypt',
 'Macau Peninsula | China',
 'Madaripur | Bangladesh',
 'Maghagha | Egypt',
 'Magura | Bangladesh',
 'Mahd Al Thahab | Saudi Arabia',
 'Majardah | Saudi Arabia',
 'Maji | Ethiopia',
 'Majmaah | Saudi Arabia',
 'Makati | Philippines',
 'Makhanda | South Africa',
 'Mandaluyong | Philippines',
 'Mandaue | Philippines',
 'Mangaluru | India',
 'Mansoura | Egypt',
 'Marawi | Philippines',
 'Margao | India',
 'Marikina | Philippines',
 'Marsa Alam | Egypt',
 'Masbate City | Philippines',
 'Mastung | Pakistan',
 'Mbombela | South Africa',
 'Mekelle | Ethiopia',
 'Menouf | Egypt',
 'Mersa Matruh | Egypt',
 'Metoubes | Egypt',
 'Mille | Ethiopia',
 'Mingora | Pakistan',
 'Minya El Qamh | Egypt',
 'Minya | Egypt',
 'Mokopane | South Africa',
 'Moulvibazar | Bangladesh',
 'Mungyeong | South Korea',
 'Muntinlupa | Philippines',
 'Muzahmiyya | Saudi Arabia',
 'Mysuru | India',
 'Naberezhnye Chelny | Russia',
 'Naga Hammadi | Egypt',
 'Naharlagun | India',
 'Nainital | India',
 'Namwon | South Korea',
 'Namyangju | South Korea',
 'Nankoku | Japan',
 'Nariyah | Saudi Arabia',
 'Nashik | India',
 'Natore | Bangladesh',
 'Natori | Japan',
 'Naucalpan | Mexico',
 'Nekemte | Ethiopia',
 'Netrokona | Bangladesh',
 'New Cairo | Egypt',
 'New Damietta | Egypt',
 'Newcastle upon Tyne | United Kingdom',
 'Newtownabbey | United Kingdom',
 'Nilphamari | Bangladesh',
 'Nishinomiya | Japan',
 'Nizhny Novgorod | Russia',
 'Nizhny Tagil | Russia',
 'Noakhali | Bangladesh',
 'Nonsan | South Korea',
 'Nonthaburi | Thailand',
 'Nova Iguacu | Brazil',
 'Nuevo Vallarta | Mexico',
 'Nuweiba | Egypt',
 'Obio-Akpor | Nigeria',
 'Obour | Egypt',
 'Offenbach | Germany',
 'Ogbomosho | Nigeria',
 'Okinawa City | Japan',
 'Ondo City | Nigeria',
 'Ordos | China',
 'Oryol | Russia',
 'Ota | Nigeria',
 'Ozamiz | Philippines',
 'Palangka Raya | Indonesia',
 'Palayan | Philippines',
 'Pangkal Pinang | Indonesia',
 'Pankshin | Nigeria',
 'Paranaque | Philippines',
 'Pasay | Philippines',
 'Pasig | Philippines',
 'Petropavlovsk-Kamchatsky | Russia',
 'Phan Rang | Vietnam',
 'Phang Nga | Thailand',
 'Piet Retief | South Africa',
 'Port Fouad | Egypt',
 'Poza Rica | Mexico',
 'Qantara | Egypt',
 'Qatif | Saudi Arabia',
 'Qena | Egypt',
 'Quang Ninh | Vietnam',
 'Qurayyat | Saudi Arabia',
 'Qus | Egypt',
 'RK Puram | India',
 'Rabigh | Saudi Arabia',
 'Rahim Yar Khan | Pakistan',
 'Rajbari | Bangladesh',
 'Rangamati | Bangladesh',
 'Ranyah | Saudi Arabia',
 'Ras El Bar | Egypt',
 'Ras Gharib | Egypt',
 'Rashid | Egypt',
 'Rembang | Indonesia',
 'Rohini | India',
 'Rorainopolis | Brazil',
 'Rostov-on-Don | Russia',
 'Rourkela | India',
 'Sacheon | South Korea',
 'Sadat City | Egypt',
 'Safaga | Egypt',
 'Safwa | Saudi Arabia',
 'Saint Catherine | Egypt',
 'Sakaide | Japan',
 'Samcheok | South Korea',
 'Samtah | Saudi Arabia',
 'San Cristobal de las Casas | Mexico',
 'San Jose City | Philippines',
 'Sarat Ubaida | Saudi Arabia',
 'Sawla | Ethiopia',
 'Seongnam | South Korea',
 'Seosan | South Korea',
 'Shanghai-Baoshan | China',
 'Shanghai-Huangpu | China',
 'Shanghai-Minhang | China',
 'Shaqra | Saudi Arabia',
 'Shariatpur | Bangladesh',
 'Sharm El Sheikh | Egypt',
 'Shashamane | Ethiopia',
 'Sheikh Zayed | Egypt',
 'Sheikh Zuweid | Egypt',
 'Sheikhupura | Pakistan',
 'Shibin El Kom | Egypt',
 'Shigatse | China',
 'Shimonoseki | Japan',
 'Shorouk | Egypt',
 'Shubra El Kheima | Egypt',
 'Sialkot | Pakistan',
 'Sidoarjo | Indonesia',
 'Siheung | South Korea',
 'Siliguri | India',
 'Sisaket | Thailand',
 'Sitakunda | Bangladesh',
 'Siwa | Egypt',
 'Sohag | Egypt',
 'Sorsogon City | Philippines',
 'Southend-on-Sea | United Kingdom',
 'Sreemangal | Bangladesh',
 'Suita | Japan',
 'Suleja | Nigeria',
 'Sunshine Coast | Australia',
 'Surigao City | Philippines',
 'Swansea | United Kingdom',
 'Tagbilaran | Philippines',
 'Taguig | Philippines',
 'Tahta | Egypt',
 'Taif | Saudi Arabia',
 'Taipa | China',
 'Tambuwal | Nigeria',
 'Tamiya | Egypt',
 'Tanjung Pinang | Indonesia',
 'Tathleeth | Saudi Arabia',
 'Tayma | Saudi Arabia',
 'Teknaf | Bangladesh',
 'Tepi | Ethiopia',
 'Thakurgaon | Bangladesh',
 'Thrissur | India',
 'Tianjin-Binhai | China',
 'Tianjin-Heping | China',
 'Tianjin-Nankai | China',
 'Tianshui | China',
 'Timika | Indonesia',
 'Tiruchirappalli | India',
 'Tonghua | China',
 'Tongi | Bangladesh',
 'Tongyeong | South Korea',
 'Trece Martires | Philippines',
 'Trishal | Bangladesh',
 'Tsuen Wan | China',
 'Tsukuba | Japan',
 'Turaif | Saudi Arabia',
 'Tuxtla Gutierrez | Mexico',
 'Umerkot | Pakistan',
 'Umluj | Saudi Arabia',
 'Unaizah | Saudi Arabia',
 'Uong Bi | Vietnam',
 'Vasco da Gama | India',
 'Vehari | Pakistan',
 'Veliky Novgorod | Russia',
 "Villeneuve-d'Ascq | France",
 'Vinh Phuc | Vietnam',
 'Visakhapatnam | India',
 'Volzhsky | Russia',
 'Wadi ad-Dawasir | Saudi Arabia',
 'Wah Cantonment | Pakistan',
 'Wanju | South Korea',
 'Wardar | Ethiopia',
 'Welkite | Ethiopia',
 'Wittenberg | Germany',
 'Woldiya | Ethiopia',
 'Worabe | Ethiopia',
 'Wrexham | United Kingdom',
 'Wudil | Nigeria',
 'Xinxiang | China',
 'Xuzhou | China',
 'Yanbu | Saudi Arabia',
 'Yangju | South Korea',
 'Yatsushiro | Japan',
 'Yeongcheon | South Korea',
 'Yeongju | South Korea',
 'Yichang | China',
 'Yirgalem | Ethiopia',
 'Yokote | Japan',
 'Yongin | South Korea',
 'Zagazig | Egypt',
 'Zulfi | Saudi Arabia',
 'eMalahleni | South Africa'}

In [220]:
len(required_cities.intersection(available_cities))

1805

In [221]:
city = city.drop_duplicates(subset="id")

In [222]:
used_cities = city[city["id"].isin(required_cities)].reset_index()
used_cities

,index,city,city_ascii,country,lat,lon,id
0,4,Guangzhou,Guangzhou,China,23.130000,113.260000,Guangzhou | China
1,5,Mumbai,Mumbai,India,19.075800,72.877500,Mumbai | India
2,6,Manila,Manila,Philippines,14.595800,120.977200,Manila | Philippines
3,8,São Paulo,Sao Paulo,Brazil,-23.550400,-46.633900,Sao Paulo | Brazil
4,9,Seoul,Seoul,South Korea,37.560000,126.990000,Seoul | South Korea
...,...,...,...,...,...,...,...
1800,49992,Jakarta Pusat,Jakarta Pusat,Indonesia,-6.177700,106.840300,Jakarta Pusat | Indonesia
1801,49993,Chongqing-Yuzhong,Chongqing-Yuzhong,China,29.560454,106.573400,Chongqing-Yuzhong | China
1802,49994,Beijing-Chaoyang,Beijing-Chaoyang,China,39.925494,116.441630,Beijing-Chaoyang | China
1803,49995,Shanghai-Pudong,Shanghai-Pudong,China,31.234722,121.506389,Shanghai-Pudong | China
1804,49996,New York City,New York City,United States,40.694300,-73.924900,New York City | United States

In [223]:
import plotly.express as px

fig = px.scatter_geo(
    used_cities,
    lat="lat",
    lon="lon",
    hover_name="id"
)

fig.show()